version: 2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch-curl
    environment:
      LISP: sbcl-bin
    steps:
       - checkout
       - run: PATH=~/.roswell/bin:$PATH
       - run: curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | bash
       - run: echo "(:tree \"$CIRCLE_WORKING_DIRECTORY/\")" > "$HOME/.config/common-lisp/source-registry.conf.d/ci.conf"
       - run: roswell/run-fiveam.ros -l ci-utils/test :circleci-tests :base-tests
