### Example configuration for Gitlab CI ###

# This is the part that is shared between all jobs
.test:
  before_script:
    - PATH=$HOME/.roswell/bin:$PATH
    - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | bash
    - ros install neil-lindquist/ci-utils # for run-fiveam and asdf-register-project
    #- ros install prove # for run-prove
    #- ros install rove # for [run-] rove
    - asdf-register-project

  script:
    - run-fiveam -e t -l foo/test :foo-tests
    #- run-prove foo.asd
    #- rove foo.asd


# Each job requires a seperate top level form that extends .test

test-sbcl:
  extends: .test
  variables:
    LISP: sbcl-bin

test-ccl:
  extends: .test
  variables:
    LISP: ccl-bin
