### Example configuration for Github Actions ###
name: CI

# Github Actions allows for running jobs on a wide variety of events
on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Test Framework
        run: ros install neil-lindquist/ci-utils
#        run: ros install prove # for run-prove:
#        run:  ros install rove # for [run-] rove
      - name: Run tests
        run: run-fiveam -e t -l foo/test :foo-tests
        #run: run-prove foo.asd
        #run: rove foo.asd
