name: CI

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Run tests
        run: roswell/run-fiveam.ros -l ci-utils/test :github-actions-tests :noncoveralls-tests :base-tests

      - name: Run-test-forms tests
        run: |
          # put test systems where asdf can find them
          cp -av t ~/lisp/

          # should fail

          roswell/run-test-forms.ros -l ci-utils-test-systems "(ci-utils-test-system:return-nil)"
          if [ $? -eq 1 ] then echo OK: $? else echo BAD: $? ; exit 1 fi
          roswell/run-test-forms.ros -l ci-utils-test-systems "(ci-utils-test-system:return-x nil)"
          if [ $? -eq 1 ] then echo OK: $? else echo BAD: $? ; exit 1 fi
          roswell/run-test-forms.ros -l ci-utils-test-systems "(ci-utils-test-system:return-not-x 123)"
          if [ $? -eq 1 ] then echo OK: $? else echo BAD: $? ; exit 1 fi

          # should succeed

          roswell/run-test-forms.ros -l ci-utils-test-systems "(ci-utils-test-system:return-t)"
          if [ $? -eq 0 ] then echo OK: $? else echo BAD: $? ; exit 1 fi

          roswell/run-test-forms.ros -l ci-utils-test-systems "(ci-utils-test-system:return-x 123)"
          if [ $? -eq 0 ] then echo OK: $? else echo BAD: $? ; exit 1 fi

          roswell/run-test-forms.ros -l ci-utils-test-systems "(ci-utils-test-system:return-not-x nil)"
          if [ $? -eq 0 ] then echo OK: $? else echo BAD: $? ; exit 1 fi

          # should error

          roswell/run-test-forms.ros -l ci-utils-test-systems "(:incomplete-form"
          if [ $? -eq 2 ] then echo OK else exit 1 fi

          roswell/run-test-forms.ros -l ci-utils-test-systems '(error "error!")'
          if [ $? -eq 2 ] then echo OK else exit 1 fi

          # dependency should error
          roswell/run-test-forms.ros -l ci-utils-test-systems/compile-error "(ci-utils-test-system:return-t)"
          if [ $? -eq 3 ] then echo OK else exit 1 fi

          roswell/run-test-forms.ros -l ci-utils-test-systems/load-error "(ci-utils-test-system:return-t)"
          if [ $? -eq 3 ] then echo OK else exit 1 fi

          roswell/run-test-forms.ros -l ci-utils-test-systems/compile-warn "(ci-utils-test-system:return-t)"
          if [ $? -eq 3 ] then echo OK else exit 1 fi

          # should succeed?
          roswell/run-test-forms.ros -l ci-utils-test-systems/load-warn "(ci-utils-test-system:return-t)"
          if [ $? -eq 0 ] then echo OK else exit 1 fi

